### ISSUE TITLE
Make this bad boy responsive

### ISSUE THREAD

**Issue by jerrywalters** [jerrywalters/api-review#1]
## Description
Add responsive styles and refactor the existing styles to be mobile first.

### Todo List
- [ ] fix padding + position of search bar on smaller screen sizes
- [ ] design responsive filters
- [ ] code responsive filters
- [ ] design responsive table
- [ ] code responsive table

**Comment by jerrywalters** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;4nR2Yb68&#x2F;11-responsive-styles"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Responsive Styles</a>
